// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	internalmodel "github.com/H1dEx/go-rocket/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	model "github.com/H1dEx/go-rocket/order/internal/repository/model"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, params
func (_m *OrderRepository) CreateOrder(ctx context.Context, params model.OrderCreateParam) (internalmodel.Order, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 internalmodel.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderCreateParam) (internalmodel.Order, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderCreateParam) internalmodel.Order); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(internalmodel.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OrderCreateParam) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - params model.OrderCreateParam
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, params interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, params)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, params model.OrderCreateParam)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderCreateParam))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 internalmodel.Order, _a1 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, model.OrderCreateParam) (internalmodel.Order, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function with given fields: ctx, id
func (_m *OrderRepository) GetOrderByID(ctx context.Context, id string) (internalmodel.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 internalmodel.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (internalmodel.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) internalmodel.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(internalmodel.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type OrderRepository_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *OrderRepository_Expecter) GetOrderByID(ctx interface{}, id interface{}) *OrderRepository_GetOrderByID_Call {
	return &OrderRepository_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, id)}
}

func (_c *OrderRepository_GetOrderByID_Call) Run(run func(ctx context.Context, id string)) *OrderRepository_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrderByID_Call) Return(_a0 internalmodel.Order, _a1 error) *OrderRepository_GetOrderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderByID_Call) RunAndReturn(run func(context.Context, string) (internalmodel.Order, error)) *OrderRepository_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, params
func (_m *OrderRepository) UpdateOrder(ctx context.Context, params internalmodel.OrderUpdateParam) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, internalmodel.OrderUpdateParam) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - params internalmodel.OrderUpdateParam
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, params interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, params)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, params internalmodel.OrderUpdateParam)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internalmodel.OrderUpdateParam))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(_a0 error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, internalmodel.OrderUpdateParam) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
